# Generated by Django 6.0.6 on 2026-07-02 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('M', 'MANAGER'), ('E', 'EMPLOYEE')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.FloatField(default=0)),
                ('date_created', models.DateField(blank=True, default=None, null=True, verbose_name='Date Of Expense')),
                ('category', models.CharField(max_length=25)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseManager.user', to_field='email')),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_id', models.IntegerField()),
                ('status', models.CharField(choices=[('P', 'PENDING'), ('A', 'APPROVED'), ('D', 'DENIED')], default='P', max_length=1)),
                ('date_approved', models.DateField(blank=True, default=None, null=True, verbose_name='Date Of Review')),
                ('comment', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExpenseManager.user', to_field='email')),
            ],
        ),
    ]
