# Generated by Django 6.0.6 on 2026-07-02 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ExpenseManager.user', to_field='email'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ExpenseManager.user', to_field='email'),
        ),
    ]
