# Generated by Django 6.0.6 on 2026-07-02 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseManager', '0002_alter_approval_reviewer_alter_expense_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approval',
            old_name='date_approved',
            new_name='dateReviewed',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='date_created',
            new_name='dateofExpense',
        ),
    ]
